version: "3.7"

services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_db
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
  server:
    image: java-test
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/spring_db?autoReconnect=true&useSSL=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    restart: always
    depends_on:
      - mysqldb
    networks:
      - backend

volumes:
  db-data:
networks:
  backend:
